I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 130, in script
    z "Um...hi"
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
IOError: Couldn't find file 'audio/urban.wav'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 130, in script
    z "Um...hi"
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/ast.py", line 689, in execute
    statement_name(stmt_name)
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/ast.py", line 46, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/exports.py", line 1684, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/display/core.py", line 2762, in do_with
    clear=clear)
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/display/core.py", line 4025, in interact_core
    renpy.audio.audio.periodic()
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/audio/audio.py", line 1162, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/audio/audio.py", line 1140, in periodic_thread_main
    periodic_pass()
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/audio/audio.py", line 1082, in periodic_pass
    c.periodic()
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/audio/audio.py", line 518, in periodic
    topf = load(filename)
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/audio/audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "/Users/cdean248345/renpy-7.4.11-sdk/renpy/loader.py", line 798, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'audio/urban.wav'.

Darwin-21.4.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
Zombie or Not 1.0
Tue May 10 14:06:31 2022
